/* AUTO-GENERATED by scripts/convert-template.mjs — do not edit */
export type TemplatePageMeta = {
  route: string;
  file: string;
  slug: string;
  title: string;
  bodyClass: string;
};

export const TEMPLATE_PAGES: TemplatePageMeta[] = [
  {
    "route": "/",
    "file": "index.html",
    "slug": "index",
    "title": "REOVANA — Foreclosed Homes",
    "bodyClass": "popup-loader theme-color-4"
  },
  {
    "route": "/home/02",
    "file": "home02.html",
    "slug": "home__02",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "counter-scroll theme-color-4"
  },
  {
    "route": "/home/03",
    "file": "home03.html",
    "slug": "home__03",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/home/04",
    "file": "home04.html",
    "slug": "home__04",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/home/05",
    "file": "home05.html",
    "slug": "home__05",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/home/06",
    "file": "home06.html",
    "slug": "home__06",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "default-dark theme-color-4"
  },
  {
    "route": "/home/07",
    "file": "home07.html",
    "slug": "home__07",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/home/08",
    "file": "home08.html",
    "slug": "home__08",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/home/09",
    "file": "home09.html",
    "slug": "home__09",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/home/10",
    "file": "home10.html",
    "slug": "home__10",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/listing/grid-full-width",
    "file": "property-grid-full-width.html",
    "slug": "listing__grid-full-width",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/listing/grid-top-search",
    "file": "property-gird-top-search.html",
    "slug": "listing__grid-top-search",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/listing/grid-left-sidebar",
    "file": "property-gird-left-sidebar.html",
    "slug": "listing__grid-left-sidebar",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/listing/grid-right-sidebar",
    "file": "property-gird-right-sidebar.html",
    "slug": "listing__grid-right-sidebar",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/listing/list-full-width",
    "file": "property-list-full-width.html",
    "slug": "listing__list-full-width",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/listing/list-top-search",
    "file": "property-list-top-search.html",
    "slug": "listing__list-top-search",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/listing/list-left-sidebar",
    "file": "property-list-left-sidebar.html",
    "slug": "listing__list-left-sidebar",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/listing/list-right-sidebar",
    "file": "property-list-right-sidebar.html",
    "slug": "listing__list-right-sidebar",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/listing/half-map-grid",
    "file": "property-half-map-grid.html",
    "slug": "listing__half-map-grid",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/listing/half-map-list",
    "file": "property-half-map-list.html",
    "slug": "listing__half-map-list",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/listing/half-top-map",
    "file": "property-half-top-map.html",
    "slug": "listing__half-top-map",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/listing/filter-popup",
    "file": "property-filter-popup.html",
    "slug": "listing__filter-popup",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/listing/filter-popup-left",
    "file": "property-filter-popup-left.html",
    "slug": "listing__filter-popup-left",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/listing/filter-popup-right",
    "file": "property-filter-popup-right.html",
    "slug": "listing__filter-popup-right",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/property/detail/v1",
    "file": "property-detail-v1.html",
    "slug": "property__detail__v1",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/property/detail/v2",
    "file": "property-detail-v2.html",
    "slug": "property__detail__v2",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/property/detail/v3",
    "file": "property-detail-v3.html",
    "slug": "property__detail__v3",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/property/detail/v4",
    "file": "property-detail-v4.html",
    "slug": "property__detail__v4",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/property/detail/v5",
    "file": "property-detail-v5.html",
    "slug": "property__detail__v5",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/agents",
    "file": "agents.html",
    "slug": "agents",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/agents/details",
    "file": "agents-details.html",
    "slug": "agents__details",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/agency/grid",
    "file": "agency-grid.html",
    "slug": "agency__grid",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/agency/list",
    "file": "agency-list.html",
    "slug": "agency__list",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/agency/details",
    "file": "agency-details.html",
    "slug": "agency__details",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/blog/grid",
    "file": "blog-grid.html",
    "slug": "blog__grid",
    "title": "Foreclosure Insights — REOVANA",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/blog/list",
    "file": "blog-list.html",
    "slug": "blog__list",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/blog/details",
    "file": "blog-details.html",
    "slug": "blog__details",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/project/list",
    "file": "project-list.html",
    "slug": "project__list",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/project/details",
    "file": "project-details.html",
    "slug": "project__details",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/contact",
    "file": "contact.html",
    "slug": "contact",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/faq",
    "file": "faq.html",
    "slug": "faq",
    "title": "FAQ — REOVANA",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/career",
    "file": "career.html",
    "slug": "career",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/compare",
    "file": "compare.html",
    "slug": "compare",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/home-loan-process",
    "file": "home-loan-process.html",
    "slug": "home-loan-process",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  },
  {
    "route": "/dashboard",
    "file": "dashboard.html",
    "slug": "dashboard",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "bg-dashboard theme-color-4"
  },
  {
    "route": "/add-property",
    "file": "add-property.html",
    "slug": "add-property",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "bg-dashboard theme-color-4"
  },
  {
    "route": "/my-property",
    "file": "my-property.html",
    "slug": "my-property",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "bg-dashboard theme-color-4"
  },
  {
    "route": "/my-profile",
    "file": "my-profile.html",
    "slug": "my-profile",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "bg-dashboard theme-color-4"
  },
  {
    "route": "/my-favorites",
    "file": "my-favorites.html",
    "slug": "my-favorites",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "bg-dashboard theme-color-4"
  },
  {
    "route": "/my-package",
    "file": "my-package.html",
    "slug": "my-package",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "bg-dashboard theme-color-4"
  },
  {
    "route": "/my-save-search",
    "file": "my-save-search.html",
    "slug": "my-save-search",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "bg-dashboard theme-color-4"
  },
  {
    "route": "/review",
    "file": "review.html",
    "slug": "review",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "bg-dashboard theme-color-4"
  },
  {
    "route": "/template-404",
    "file": "404.html",
    "slug": "template-404",
    "title": "Proty - Real Estate HTML Template",
    "bodyClass": "theme-color-4"
  }
];

export const ROUTE_TO_SLUG: Record<string, string> = {
  "/": "index",
  "/home/02": "home__02",
  "/home/03": "home__03",
  "/home/04": "home__04",
  "/home/05": "home__05",
  "/home/06": "home__06",
  "/home/07": "home__07",
  "/home/08": "home__08",
  "/home/09": "home__09",
  "/home/10": "home__10",
  "/listing/grid-full-width": "listing__grid-full-width",
  "/listing/grid-top-search": "listing__grid-top-search",
  "/listing/grid-left-sidebar": "listing__grid-left-sidebar",
  "/listing/grid-right-sidebar": "listing__grid-right-sidebar",
  "/listing/list-full-width": "listing__list-full-width",
  "/listing/list-top-search": "listing__list-top-search",
  "/listing/list-left-sidebar": "listing__list-left-sidebar",
  "/listing/list-right-sidebar": "listing__list-right-sidebar",
  "/listing/half-map-grid": "listing__half-map-grid",
  "/listing/half-map-list": "listing__half-map-list",
  "/listing/half-top-map": "listing__half-top-map",
  "/listing/filter-popup": "listing__filter-popup",
  "/listing/filter-popup-left": "listing__filter-popup-left",
  "/listing/filter-popup-right": "listing__filter-popup-right",
  "/property/detail/v1": "property__detail__v1",
  "/property/detail/v2": "property__detail__v2",
  "/property/detail/v3": "property__detail__v3",
  "/property/detail/v4": "property__detail__v4",
  "/property/detail/v5": "property__detail__v5",
  "/agents": "agents",
  "/agents/details": "agents__details",
  "/agency/grid": "agency__grid",
  "/agency/list": "agency__list",
  "/agency/details": "agency__details",
  "/blog/grid": "blog__grid",
  "/blog/list": "blog__list",
  "/blog/details": "blog__details",
  "/project/list": "project__list",
  "/project/details": "project__details",
  "/contact": "contact",
  "/faq": "faq",
  "/career": "career",
  "/compare": "compare",
  "/home-loan-process": "home-loan-process",
  "/dashboard": "dashboard",
  "/add-property": "add-property",
  "/my-property": "my-property",
  "/my-profile": "my-profile",
  "/my-favorites": "my-favorites",
  "/my-package": "my-package",
  "/my-save-search": "my-save-search",
  "/review": "review",
  "/template-404": "template-404"
};

export const SLUG_TO_ROUTE: Record<string, string> = {
  "index": "/",
  "home__02": "/home/02",
  "home__03": "/home/03",
  "home__04": "/home/04",
  "home__05": "/home/05",
  "home__06": "/home/06",
  "home__07": "/home/07",
  "home__08": "/home/08",
  "home__09": "/home/09",
  "home__10": "/home/10",
  "listing__grid-full-width": "/listing/grid-full-width",
  "listing__grid-top-search": "/listing/grid-top-search",
  "listing__grid-left-sidebar": "/listing/grid-left-sidebar",
  "listing__grid-right-sidebar": "/listing/grid-right-sidebar",
  "listing__list-full-width": "/listing/list-full-width",
  "listing__list-top-search": "/listing/list-top-search",
  "listing__list-left-sidebar": "/listing/list-left-sidebar",
  "listing__list-right-sidebar": "/listing/list-right-sidebar",
  "listing__half-map-grid": "/listing/half-map-grid",
  "listing__half-map-list": "/listing/half-map-list",
  "listing__half-top-map": "/listing/half-top-map",
  "listing__filter-popup": "/listing/filter-popup",
  "listing__filter-popup-left": "/listing/filter-popup-left",
  "listing__filter-popup-right": "/listing/filter-popup-right",
  "property__detail__v1": "/property/detail/v1",
  "property__detail__v2": "/property/detail/v2",
  "property__detail__v3": "/property/detail/v3",
  "property__detail__v4": "/property/detail/v4",
  "property__detail__v5": "/property/detail/v5",
  "agents": "/agents",
  "agents__details": "/agents/details",
  "agency__grid": "/agency/grid",
  "agency__list": "/agency/list",
  "agency__details": "/agency/details",
  "blog__grid": "/blog/grid",
  "blog__list": "/blog/list",
  "blog__details": "/blog/details",
  "project__list": "/project/list",
  "project__details": "/project/details",
  "contact": "/contact",
  "faq": "/faq",
  "career": "/career",
  "compare": "/compare",
  "home-loan-process": "/home-loan-process",
  "dashboard": "/dashboard",
  "add-property": "/add-property",
  "my-property": "/my-property",
  "my-profile": "/my-profile",
  "my-favorites": "/my-favorites",
  "my-package": "/my-package",
  "my-save-search": "/my-save-search",
  "review": "/review",
  "template-404": "/template-404"
};

export function getTemplateMetaByRoute(route: string): TemplatePageMeta | undefined {
  return TEMPLATE_PAGES.find((p) => p.route === route);
}

export function getTemplateMetaBySlug(slug: string): TemplatePageMeta | undefined {
  return TEMPLATE_PAGES.find((p) => p.slug === slug);
}
